Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:

1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
array=np.empty((2,2))
array.shape



array([[4.97210477e-310, 0.00000000e+000],
       [4.97119636e-310, 6.86914029e-310]])

2. Initialize an all one array with size 4X2.

In [ ]:
array=np.ones((4,2))
array.shape
array


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
array=np.full((4,3),3)
array

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
initial_array=np.arange(6).reshape(2,3)
initial_array
array=np.zeros_like(initial_array)
array

array([[0, 0, 0],
       [0, 0, 0]])

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
initial_array=np.arange(8).reshape(2,4)
array=np.ones_like(initial_array)
array

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list=[1,2,3,4]
array=np.array(new_list)
array

array([1, 2, 3, 4])

4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
array=np.arange(10,50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
array=np.arange(0,9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
array=np.eye(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np
array = np.random.random(30)
mean = array.mean()

print("Random array: ", array)
print("Mean of array: ", mean)


Random array:  [0.4910031  0.98812777 0.80737325 0.20833294 0.29690329 0.7529268
 0.18848008 0.55669745 0.39464322 0.17773231 0.2988705  0.48942434
 0.29459411 0.26285683 0.59274228 0.16787503 0.68485747 0.43110301
 0.0566736  0.35921813 0.15714593 0.10358011 0.05824547 0.67984743
 0.88957005 0.27277156 0.32310683 0.57483342 0.49352371 0.40079935]
Mean of array:  0.41512864572073954


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
array=np.random.random((10,10))
min_value=array.min()
max_value=array.max()
print("10x10 Random Array:\n", array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

10x10 Random Array:
 [[0.19631286 0.51731636 0.90615416 0.03612955 0.21689512 0.28392222
  0.56996602 0.51677124 0.29430797 0.00117335]
 [0.27657633 0.63214215 0.99419421 0.3660541  0.09605255 0.83261157
  0.22579307 0.31037967 0.12838928 0.71260208]
 [0.08406482 0.45733618 0.4380922  0.97786597 0.7979835  0.67433567
  0.72167156 0.46316344 0.01455759 0.16342164]
 [0.31043648 0.17363829 0.15253198 0.23316845 0.40293461 0.3888388
  0.20972407 0.6277486  0.19410162 0.66740666]
 [0.74518728 0.176846   0.69101876 0.89502419 0.14088827 0.90275755
  0.55282316 0.93374721 0.62034648 0.57089486]
 [0.83761934 0.84668998 0.40173625 0.75180619 0.29136328 0.135878
  0.09756475 0.75895259 0.63606104 0.89901555]
 [0.33978407 0.84629092 0.8189276  0.31900054 0.52856789 0.4968078
  0.16053929 0.09484222 0.62362732 0.07689432]
 [0.14555438 0.47507206 0.16094155 0.50811697 0.82636638 0.02054311
  0.42624258 0.8214425  0.86294337 0.18432296]
 [0.3764561  0.33728449 0.79203401 0.36741127 0.00752549 0.8071

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
array=np.zeros(10)
array[4]=1
print("Updated array:", array)

Updated array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr=np.array([1,2,0,0,4,0])
reversed_arr=arr[::-1]
print("Original array: ", arr)
print("reversed array: ", reversed_arr)

Original array:  [1 2 0 0 4 0]
reversed array:  [0 4 0 0 2 1]


8.Create a 2d array with 1 on border and 0 inside.

In [ ]:
arr=np.zeros((5,5),dtype=int)
arr[0,:]=1 #top
arr[-1,:]=1 #bottom
arr[:,0]=1 #left
arr[:,-1]=1 #right
print("2D array with 1 on border and 0 inside: \n",arr)


2D array with 1 on border and 0 inside: 
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9.Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
board=np.zeros((8,8), dtype=int)
board[1::2,::2]=1
board[::2,1::2]=1
print(board)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:

1. Add the two array.

In [ ]:
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("x: \n",x)
print("y: \n",y)
add=x+y
addition=v+w
print("Adding x+y: \n",add)
print("v: \n",v)
print("w: \n",w)
print("adding v+w: ",addition)

x: 
 [[1 2]
 [3 5]]
y: 
 [[5 6]
 [7 8]]
Adding x+y: 
 [[ 6  8]
 [10 13]]
v: 
 [ 9 10]
w: 
 [11 12]
adding v+w:  [20 22]


2. Subtract the two array.

In [ ]:
sub=x-y
subtract=v-w
print("subtracting y from x: ",sub)
print("subtracting w from v: ",subtract)

subtracting y from x:  [[-4 -4]
 [-4 -3]]
subtracting w from v:  [-2 -2]


3. Multiply the array with any integers of your choice.

In [ ]:
mul_x=x*2
print("x: \n",mul_x)
mul_y=y*2
print("y: \n",mul_y)
mul_w=w*2
print("w: \n",mul_w)
mul_v=v*2
print("v: \n",mul_v)

x: 
 [[ 2  4]
 [ 6 10]]
y: 
 [[10 12]
 [14 16]]
w: 
 [22 24]
v: 
 [18 20]


4. Find the square of each element of the array.

In [ ]:
sq_x=np.square(x)
print("squaring x: \n",sq_x )
sq_y=np.square(y)
print("squaring y: \n",sq_y )
sq_v=np.square(v)
print("squaring v: \n",sq_v )
sq_w=np.square(w)
print("squaring w: \n",sq_w )




squaring x: 
 [[ 1  4]
 [ 9 25]]
squaring y: 
 [[25 36]
 [49 64]]
squaring v: 
 [ 81 100]
squaring w: 
 [121 144]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
result_vw = np.dot(v, w)
print("Dot product of v and w: \n", result_vw)
result_xv = np.dot(x, v)
print("Dot product of x and v:\n", result_xv)
result_xy = np.dot(x, y)
print("Dot product of x and y:\n", result_xy)


Dot product of v and w: 
 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
arr=np.concatenate((x,y),axis=1)
print("along row: \n",arr)
array=np.vstack((v,w))
print("along column: \n",array)

along row: 
 [[1 2 5 6]
 [3 5 7 8]]
along column: 
 [[ 9 10]
 [11 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
result = np.concatenate((x, v))
print("Concatenation result:\n", result)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

x is a 2D array whereas v is a 1D array. We cannot directly concatenate a 2D array and a 1D array because The np.concatenate() function requires that the arrays being concatenated must have the same number of dimensions and in this case, both should be 2D arrays. Therefore, we get error.


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A^−1 = I


In [4]:
import numpy as np
A=np.array([[3,4],[7,8]])
B=np.array([[5,3],[2,1]])
A_inv=np.linalg.inv(A)
result=np.dot(A,A_inv)
identity_matrix=np.eye(2)
print("Matrix A:\n", A)
print("Inverse of A (A^-1):\n", A_inv)
print("Product of A and A^-1 (A.A^-1):\n", result)
print("Identity Matrix:\n", identity_matrix)
y=np.allclose(result,identity_matrix)
print("Is A.A^-1 equal to identity matrix?->",y)


Matrix A:
 [[3 4]
 [7 8]]
Inverse of A (A^-1):
 [[-2.    1.  ]
 [ 1.75 -0.75]]
Product of A and A^-1 (A.A^-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix:
 [[1. 0.]
 [0. 1.]]
Is A.A^-1 equal to identity matrix?-> True


2. Prove AB ̸= BA.

In [5]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB (A * B):\n", AB)
print("BA (B * A):\n", BA)
are_equal=np.array_equal(AB,BA)
print(" Is AB = BA? ",are_equal)

AB (A * B):
 [[23 13]
 [51 29]]
BA (B * A):
 [[36 44]
 [13 16]]
 Is AB = BA?  False


 3. Prove (AB)^T=B^T*A^T

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
AB=np.dot(A,B)
AB_T=AB.T
B_T=B.T
A_T=A.T
BT_AT=np.dot(B_T,A_T)
print("AB:\n", AB)
print("(AB)^T:\n", AB_T)
print("B^T:\n", B_T)
print("A^T:\n", A_T)
print("B^T * A^T:\n", BT_AT)
is_equal=np.array_equal(AB_T,BT_AT)
print("Is (AB)^T equal to B^T * A^T? ", is_equal)

AB:
 [[19 22]
 [43 50]]
(AB)^T:
 [[19 43]
 [22 50]]
B^T:
 [[5 7]
 [6 8]]
A^T:
 [[1 3]
 [2 4]]
B^T * A^T:
 [[19 43]
 [22 50]]
Is (AB)^T equal to B^T * A^T?  True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [5]:
import numpy as np
A=np.array([[2,-3,1], [1,-1,2], [3,1,-1]])
B=np.array([-1,-3,9])
A_inv=np.linalg.inv(A)
x=np.dot(A_inv,B)
print("Coefficient Matrix (A):\n", A)
print("Constants Vector (B):\n", B)
print("Inverse of A (A^-1):\n", A_inv)
print("Solution Vector (X):\n", x)

[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Coefficient Matrix (A):
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constants Vector (B):
 [-1 -3  9]
Inverse of A (A^-1):
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
Solution Vector (X):
 [ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [7]:
import numpy as np
import time
list1=list(range(1,1000001))
list2=list(range(1,1000001))
start_time= time.time()
result_list=[a+b for a, b in zip(list1,list2)]
python_time=time.time()-start_time
print("Time taken for element-wise addition using Python lists:", python_time, "seconds")
#numpy arrays:
arr1=np.arange(1,1000001)
arr2=np.arange(1,1000001)

start_time=time.time()
result_array=arr1+arr2
numpy_time=time.time()-start_time
print("Time taken for element-wise addition using NumPy arrays:", numpy_time, "seconds")



Time taken for element-wise addition using Python lists: 0.20983576774597168 seconds
Time taken for element-wise addition using NumPy arrays: 0.009667634963989258 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [9]:
import numpy as np
import time
list1=list(range(1,1000001))
list2=list(range(1,1000001))
start_time=time.time()
result_list=[a*b for a,b in zip(list1,list2)]
python_time=time.time()-start_time
print("Time taken for element-wise multiplication using Python lists:", python_time, "seconds")

# NumPy arrays:
arr1 = np.arange(1, 1000001)
arr2 = np.arange(1, 1000001)

start_time = time.time()
result_array = arr1 * arr2
numpy_time = time.time() - start_time
print("Time taken for element-wise multiplication using NumPy arrays:", numpy_time, "seconds")


Time taken for element-wise multiplication using Python lists: 0.14147233963012695 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.004624605178833008 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [11]:
import numpy as np
import time

list1 = list(range(1, 1000001))
list2 = list(range(1, 1000001))
start_time = time.time()
dot_product_list = sum(a * b for a, b in zip(list1, list2))
python_time = time.time() - start_time
print("Time taken for dot product using Python lists:", python_time, "seconds")
arr1 = np.arange(1, 1000001)
arr2 = np.arange(1, 1000001)

# dot product using NumPy arrays
start_time = time.time()
dot_product_numpy = np.dot(arr1, arr2)
numpy_time = time.time() - start_time
print("Time taken for dot product using NumPy arrays: ", numpy_time, "seconds")

Time taken for dot product using Python lists: 0.10646963119506836 seconds
Time taken for dot product using NumPy arrays:  0.0018224716186523438 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [15]:
import numpy as np
import time


matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]


start_time = time.time()

result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]

python_time = time.time() - start_time
print("Time taken for matrix multiplication using Python lists: ", python_time, "seconds")

# Matrix multiplication using NumPy
matrix1_np = np.random.rand(1000, 1000)
matrix2_np = np.random.rand(1000, 1000)

start_time = time.time()

result_matrix_np = np.dot(matrix1_np, matrix2_np)

numpy_time = time.time() - start_time
print("Time taken for matrix multiplication using NumPy arrays: ", numpy_time, "seconds")


Time taken for matrix multiplication using Python lists:  259.33086585998535 seconds
Time taken for matrix multiplication using NumPy arrays:  0.06735491752624512 seconds
